name: Crash Report
description: The game crashed or hanged

body:
- type: input
  attributes:
    label: Game version
    description: "You can find this information in the bottom right corner of the main menu"
    placeholder: "0.2.1-alpha"
  validations:
    required: true
- type: input
  attributes:
    label: Operating system
    placeholder: "Windows 11"
  validations:
    required: true
