name: Crash Report
description: The game crashed or hanged

body:
- type: input
  attributes:
    label: Game version
    description: "You can find this information in the bottom right corner of the main menu"
  validations:
    required: true
