on:
  push:
    branches:
    - iwyu  # TODO: remove
    - dev
jobs:
  hello:
    runs-on: ubuntu-22.04
    steps:
    - run: apt-get install build-essential cmake libsdl2-dev libsdl2-image-dev libsdl2-ttf-dev libsndfile1-dev libvorbis-dev libogg-dev libpng-dev libglew-dev libopenal-dev libphysfs-dev gettext git po4a vorbis-tools libglm-dev
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - run: cmake -S . -B build
    - run: echo world > hello.txt
    - uses: peter-evans/create-pull-request@v7
      with:
        commit-message: Include what you use
        title: Include what you use
        branch: include-what-you-use
        body: ""
        
