on: [push]
jobs:
  hello:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - run: echo world > hello.txt
    - uses: peter-evans/create-pull-request@v7
